# Generated by Django 4.2.29 on 2026-03-21 23:29

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('none', 'No Role'), ('engineering', 'Engineering'), ('approver', 'Approver'), ('operations', 'Operations'), ('admin', 'Admin')], default='none', max_length=20),
        ),
    ]
