# Generated by Django 5.2.6 on 2026-03-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECOStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('is_default_new', models.BooleanField(default=False)),
                ('is_default_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
