# Generated by Django 4.2.29 on 2026-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecostage',
            name='sequence',
            field=models.IntegerField(unique=True),
        ),
    ]
