# Generated by Django 5.2.6 on 2026-03-21 07:04

import django.db.models.deletion  # type: ignore
from django.conf import settings  # type: ignore
from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bom', '0001_initial'),
        ('products', '0001_initial'),
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('eco_type', models.CharField(choices=[('product', 'Product'), ('bom', 'Bill of Materials')], max_length=20)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('version_update', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('applied', 'Applied')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecos', to='bom.bom')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecos', to='products.product')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.ecostage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ECOProposedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('bom', 'BOM')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('eco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_changes', to='eco.eco')),
            ],
        ),
    ]
