# Generated by Django 4.2.29 on 2026-03-21 17:52

from django.db import migrations  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_add_eco_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eco',
            name='eco_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='eco',
            name='eco_product_status_idx',
        ),
    ]
