# Generated by Django 4.2.29 on 2026-03-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0003_remove_eco_eco_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoproposedchange',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Product'), ('bom', 'BOM'), ('bomcomponent', 'BOM Component')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='eco',
            index=models.Index(fields=['status'], name='eco_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eco',
            index=models.Index(fields=['product', 'status'], name='eco_product_status_idx'),
        ),
    ]
