# Generated by Django 4.2.29 on 2026-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0004_alter_ecoproposedchange_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eco',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
