# Generated by Django 4.2.29 on 2026-03-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_audit_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_event_time_idx',
        ),
    ]
