# Generated by Django 4.2.29 on 2026-03-21 18:19

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_remove_auditlog_audit_event_time_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='audit_event_time_idx'),
        ),
    ]
