# Generated by Django 5.2.6 on 2026-03-21 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eco', '0001_initial'),
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional')], max_length=20)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='settings_app.ecostage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('stage', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('eco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='eco.eco')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_app.ecostage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('eco', 'stage', 'user')},
            },
        ),
    ]
