# Generated by Django 4.2.29 on 2026-03-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_ecostage_sequence'),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalconfig',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='settings_app.ecostage'),
        ),
    ]
