# Generated by Django 4.2.29 on 2026-03-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='reference',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('reference', 'version')},
        ),
    ]
