# Generated by Django 4.2.29 on 2026-03-21 19:46

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_alter_bom_reference_alter_bom_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='reference',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
